export type Language = 'en' | 'ar';

export const translations = {
  en: {
    // General
    appName: 'DriveUAE',
    tagline: 'Long-Term Car Rental Dubai',
    search: 'Search',
    filter: 'Filter',
    filters: 'Filters',
    clearAll: 'Clear All',
    apply: 'Apply',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    loading: 'Loading...',
    noResults: 'No results found',
    tryAgain: 'Try Again',
    viewAll: 'View All',
    seeMore: 'See More',
    aed: 'AED',
    perMonth: '/month',

    // Navigation
    home: 'Home',
    cars: 'Cars',
    myBookings: 'My Bookings',
    profile: 'Profile',
    support: 'Support',
    admin: 'Admin',
    dashboard: 'Dashboard',
    customers: 'Customers',
    leads: 'Leads',
    documents: 'Documents',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',

    // Home
    heroTitle: 'Premium Long-Term Car Rental in Dubai',
    heroSubtitle: 'Flexible monthly plans from 1 to 12 months. Professional service, transparent pricing.',
    searchPlaceholder: 'Search by brand, model, or type...',
    featuredCars: 'Featured Cars',
    popularCategories: 'Popular Categories',
    whyChooseUs: 'Why Choose DriveUAE',
    benefit1Title: 'Flexible Plans',
    benefit1Desc: 'Choose from 1, 3, 6, or 12 month rental periods',
    benefit2Title: 'Best Prices',
    benefit2Desc: 'Competitive monthly rates with long-term discounts',
    benefit3Title: 'Easy Booking',
    benefit3Desc: 'Simple process — browse, request, and drive',
    benefit4Title: 'Premium Fleet',
    benefit4Desc: 'Well-maintained vehicles from top brands',

    // Cars
    allCars: 'All Cars',
    monthlyPrice: 'Monthly Price',
    brand: 'Brand',
    model: 'Model',
    year: 'Year',
    seats: 'Seats',
    doors: 'Doors',
    transmission: 'Transmission',
    fuelType: 'Fuel Type',
    automatic: 'Automatic',
    manual: 'Manual',
    petrol: 'Petrol',
    diesel: 'Diesel',
    hybrid: 'Hybrid',
    electric: 'Electric',
    sedan: 'Sedan',
    suv: 'SUV',
    hatchback: 'Hatchback',
    coupe: 'Coupe',
    available: 'Available',
    rented: 'Rented',
    maintenance: 'Maintenance',
    inactive: 'Inactive',
    viewDetails: 'View Details',
    requestBooking: 'Request Booking',
    carDetails: 'Car Details',
    specifications: 'Specifications',
    features: 'Features',
    rentalPricing: 'Rental Pricing',
    rentalConditions: 'Rental Conditions',
    securityDeposit: 'Security Deposit',

    // Duration
    selectDuration: 'Select Duration',
    oneMonth: '1 Month',
    threeMonths: '3 Months',
    sixMonths: '6 Months',
    twelveMonths: '12 Months',
    totalAmount: 'Total Amount',
    youSave: 'You Save',

    // Booking
    bookingRequest: 'Booking Request',
    startDate: 'Start Date',
    endDate: 'End Date',
    duration: 'Duration',
    monthlyRent: 'Monthly Rent',
    bookingReference: 'Booking Reference',
    bookingStatus: 'Booking Status',
    pending: 'Pending',
    approved: 'Approved',
    active: 'Active',
    completed: 'Completed',
    cancelled: 'Cancelled',
    rejected: 'Rejected',
    submitRequest: 'Submit Request',
    bookingSubmitted: 'Booking Submitted Successfully',
    bookingSubmittedDesc: 'We will review your request and contact you shortly.',
    uploadDocuments: 'Upload Documents',
    documentsRequired: 'Documents Required',
    emiratesId: 'Emirates ID',
    passport: 'Passport',
    drivingLicense: 'Driving License',
    uploadFile: 'Upload File',
    fileUploaded: 'File Uploaded',
    fileRejected: 'File Rejected',
    pendingReview: 'Pending Review',

    // Auth
    email: 'Email',
    password: 'Password',
    phone: 'Phone',
    fullName: 'Full Name',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to manage your bookings',
    registerTitle: 'Create Account',
    registerSubtitle: 'Start your long-term rental journey',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    phoneOtp: 'Phone OTP',
    sendOtp: 'Send OTP',
    verifyOtp: 'Verify OTP',

    // Profile
    myProfile: 'My Profile',
    language: 'Language',
    english: 'English',
    arabic: 'العربية',
    editProfile: 'Edit Profile',

    // Support
    contactUs: 'Contact Us',
    whatsapp: 'WhatsApp',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    faq: 'FAQ',
    send: 'Send',
    message: 'Message',

    // Admin
    adminDashboard: 'Admin Dashboard',
    totalCars: 'Total Cars',
    availableCars: 'Available Cars',
    rentedCars: 'Rented Cars',
    activeRentals: 'Active Rentals',
    pendingBookings: 'Pending Bookings',
    newLeads: 'New Leads',
    revenue: 'Revenue',
    manageCars: 'Manage Cars',
    manageBookings: 'Manage Bookings',
    manageCustomers: 'Manage Customers',
    manageLeads: 'Manage Leads',
    addCar: 'Add Car',
    editCar: 'Edit Car',
    carTitle: 'Listing Title',
    category: 'Category',
    carLocation: 'Location',
    carDescription: 'Description',
    featured: 'Featured',
    published: 'Published',
    dailyPrice: 'Daily Price',
    weeklyPrice: 'Weekly Price',
    threeMonthPrice: '3-Month Price',
    sixMonthPrice: '6-Month Price',
    twelveMonthPrice: '12-Month Price',
    color: 'Color',
    imagesCommaSeparated: 'Image URLs (comma-separated)',
    featuresCommaSeparated: 'Features (comma-separated)',
    approve: 'Approve',
    reject: 'Reject',
    activate: 'Activate',
    complete: 'Complete',
    statusHistory: 'Status History',
    leadStatus: 'Lead Status',
    newLead: 'New',
    contacted: 'Contacted',
    interested: 'Interested',
    documentsPending: 'Documents Pending',
    leadApproved: 'Approved',
    booked: 'Booked',
    lost: 'Lost',
    utilization: 'Fleet Utilization',

    // Onboarding
    onboarding1Title: 'Long-Term Car Rental',
    onboarding1Desc: 'Rent premium vehicles for 1 to 12 months in Dubai',
    onboarding2Title: 'Flexible Plans',
    onboarding2Desc: 'Choose the duration that works best for you',
    onboarding3Title: 'Easy Booking',
    onboarding3Desc: 'Browse, request, upload documents, and drive',
    getStarted: 'Get Started',
    skip: 'Skip',

    // Errors
    somethingWrong: 'Something went wrong',
    tryAgainLater: 'Please try again later',
    noCarsFound: 'No cars found matching your criteria',
    clearFilters: 'Clear Filters',
    networkError: 'Network error. Please check your connection.',
  },
  ar: {
    // General
    appName: 'درايف الإمارات',
    tagline: 'تأجير سيارات طويل الأمد في دبي',
    search: 'بحث',
    filter: 'تصفية',
    filters: 'التصفية',
    clearAll: 'مسح الكل',
    apply: 'تطبيق',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    save: 'حفظ',
    edit: 'تعديل',
    delete: 'حذف',
    close: 'إغلاق',
    back: 'رجوع',
    next: 'التالي',
    submit: 'إرسال',
    loading: 'جاري التحميل...',
    noResults: 'لا توجد نتائج',
    tryAgain: 'حاول مرة أخرى',
    viewAll: 'عرض الكل',
    seeMore: 'عرض المزيد',
    aed: 'د.إ',
    perMonth: '/شهر',

    // Navigation
    home: 'الرئيسية',
    cars: 'السيارات',
    myBookings: 'حجوزاتي',
    profile: 'الملف الشخصي',
    support: 'الدعم',
    admin: 'الإدارة',
    dashboard: 'لوحة التحكم',
    customers: 'العملاء',
    leads: 'العملاء المحتملون',
    documents: 'المستندات',
    reports: 'التقارير',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',

    // Home
    heroTitle: 'تأجير سيارات فاخر طويل الأمد في دبي',
    heroSubtitle: 'خطط شهرية مرنة من 1 إلى 12 شهر. خدمة احترافية وأسعار شفافة.',
    searchPlaceholder: 'ابحث بالماركة أو الموديل أو النوع...',
    featuredCars: 'سيارات مميزة',
    popularCategories: 'الفئات الشائعة',
    whyChooseUs: 'لماذا تختار درايف الإمارات',
    benefit1Title: 'خطط مرنة',
    benefit1Desc: 'اختر من فترات تأجير 1 أو 3 أو 6 أو 12 شهر',
    benefit2Title: 'أفضل الأسعار',
    benefit2Desc: 'أسعار شهرية تنافسية مع خصومات التأجير الطويل',
    benefit3Title: 'حجز سهل',
    benefit3Desc: 'عملية بسيطة — تصفح، اطلب، وقُد',
    benefit4Title: 'أسطول متميز',
    benefit4Desc: 'سيارات مصانة جيداً من أفضل الماركات',

    // Cars
    allCars: 'جميع السيارات',
    monthlyPrice: 'السعر الشهري',
    brand: 'الماركة',
    model: 'الموديل',
    year: 'السنة',
    seats: 'المقاعد',
    doors: 'الأبواب',
    transmission: 'ناقل الحركة',
    fuelType: 'نوع الوقود',
    automatic: 'أوتوماتيك',
    manual: 'يدوي',
    petrol: 'بنزين',
    diesel: 'ديزل',
    hybrid: 'هجين',
    electric: 'كهربائي',
    sedan: 'سيدان',
    suv: 'دفع رباعي',
    hatchback: 'هاتشباك',
    coupe: 'كوبيه',
    available: 'متاحة',
    rented: 'مؤجرة',
    maintenance: 'صيانة',
    inactive: 'غير نشطة',
    viewDetails: 'عرض التفاصيل',
    requestBooking: 'طلب حجز',
    carDetails: 'تفاصيل السيارة',
    specifications: 'المواصفات',
    features: 'المميزات',
    rentalPricing: 'أسعار التأجير',
    rentalConditions: 'شروط التأجير',
    securityDeposit: 'تأمين',

    // Duration
    selectDuration: 'اختر المدة',
    oneMonth: 'شهر واحد',
    threeMonths: '3 أشهر',
    sixMonths: '6 أشهر',
    twelveMonths: '12 شهر',
    totalAmount: 'المبلغ الإجمالي',
    youSave: 'توفير',

    // Booking
    bookingRequest: 'طلب حجز',
    startDate: 'تاريخ البدء',
    endDate: 'تاريخ الانتهاء',
    duration: 'المدة',
    monthlyRent: 'الإيجار الشهري',
    bookingReference: 'رقم الحجز',
    bookingStatus: 'حالة الحجز',
    pending: 'قيد المراجعة',
    approved: 'معتمد',
    active: 'نشط',
    completed: 'مكتمل',
    cancelled: 'ملغي',
    rejected: 'مرفوض',
    submitRequest: 'إرسال الطلب',
    bookingSubmitted: 'تم إرسال الطلب بنجاح',
    bookingSubmittedDesc: 'سنراجع طلبك ونتواصل معك قريباً.',
    uploadDocuments: 'رفع المستندات',
    documentsRequired: 'المستندات المطلوبة',
    emiratesId: 'بطاقة الهوية',
    passport: 'جواز السفر',
    drivingLicense: 'رخصة القيادة',
    uploadFile: 'رفع ملف',
    fileUploaded: 'تم رفع الملف',
    fileRejected: 'تم رفض الملف',
    pendingReview: 'قيد المراجعة',

    // Auth
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    phone: 'الهاتف',
    fullName: 'الاسم الكامل',
    loginTitle: 'مرحباً بعودتك',
    loginSubtitle: 'سجل دخولك لإدارة حجوزاتك',
    registerTitle: 'إنشاء حساب',
    registerSubtitle: 'ابدأ رحلتك في التأجير طويل الأمد',
    forgotPassword: 'نسيت كلمة المرور؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    phoneOtp: 'رمز التحقق',
    sendOtp: 'إرسال الرمز',
    verifyOtp: 'تحقق من الرمز',

    // Profile
    myProfile: 'ملفي الشخصي',
    language: 'اللغة',
    english: 'English',
    arabic: 'العربية',
    editProfile: 'تعديل الملف',

    // Support
    contactUs: 'تواصل معنا',
    whatsapp: 'واتساب',
    callUs: 'اتصل بنا',
    emailUs: 'راسلنا',
    faq: 'الأسئلة الشائعة',
    send: 'إرسال',
    message: 'رسالة',

    // Admin
    adminDashboard: 'لوحة تحكم الإدارة',
    totalCars: 'إجمالي السيارات',
    availableCars: 'السيارات المتاحة',
    rentedCars: 'السيارات المؤجرة',
    activeRentals: 'التأجيرات النشطة',
    pendingBookings: 'الحجوزات المعلقة',
    newLeads: 'عملاء محتملون جدد',
    revenue: 'الإيرادات',
    manageCars: 'إدارة السيارات',
    manageBookings: 'إدارة الحجوزات',
    manageCustomers: 'إدارة العملاء',
    manageLeads: 'إدارة العملاء المحتملين',
    addCar: 'إضافة سيارة',
    editCar: 'تعديل سيارة',
    carTitle: 'عنوان الإعلان',
    category: 'الفئة',
    carLocation: 'الموقع',
    carDescription: 'الوصف',
    featured: 'مميزة',
    published: 'منشورة',
    dailyPrice: 'السعر اليومي',
    weeklyPrice: 'السعر الأسبوعي',
    threeMonthPrice: 'سعر 3 أشهر',
    sixMonthPrice: 'سعر 6 أشهر',
    twelveMonthPrice: 'سعر 12 شهر',
    color: 'اللون',
    imagesCommaSeparated: 'روابط الصور (مفصولة بفواصل)',
    featuresCommaSeparated: 'المميزات (مفصولة بفواصل)',
    approve: 'موافقة',
    reject: 'رفض',
    activate: 'تفعيل',
    complete: 'إكمال',
    statusHistory: 'سجل الحالة',
    leadStatus: 'حالة العميل المحتمل',
    newLead: 'جديد',
    contacted: 'تم التواصل',
    interested: 'مهتم',
    documentsPending: 'مستندات معلقة',
    leadApproved: 'معتمد',
    booked: 'محجوز',
    lost: 'مفقود',
    utilization: 'استخدام الأسطول',

    // Onboarding
    onboarding1Title: 'تأجير سيارات طويل الأمد',
    onboarding1Desc: 'استأجر سيارات فاخرة من 1 إلى 12 شهر في دبي',
    onboarding2Title: 'خطط مرنة',
    onboarding2Desc: 'اختر المدة المناسبة لك',
    onboarding3Title: 'حجز سهل',
    onboarding3Desc: 'تصفح، اطلب، ارفع المستندات، وقُد',
    getStarted: 'ابدأ الآن',
    skip: 'تخطي',

    // Errors
    somethingWrong: 'حدث خطأ ما',
    tryAgainLater: 'يرجى المحاولة لاحقاً',
    noCarsFound: 'لا توجد سيارات مطابقة لمعاييرك',
    clearFilters: 'مسح التصفية',
    networkError: 'خطأ في الشبكة. يرجى التحقق من اتصالك.',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
